spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: minicampus_user

  main:
    allow-bean-definition-overriding: true


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

    show-sql: true

  mail:
    host: smtp.gmail.com
    port : 587
    username: emailName
    password: ouburguvffcvkqmn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true



