spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: minicampus_user

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

    show-sql: true

  mail:
    host: smtp.gmail.com
    port : 587
    username: googleId
    password: appPassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true

logging:
  level:
    root: info

mybatis:
  mapper-locations: mybatis/**/*.xml
#  카멜표기법으로 변환
  configuration:
    map-underscore-to-camel-case : true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

