spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: minicampus_user


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

    show-sql: true
